# Generated by Django 5.0.7 on 2024-11-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
