# Generated by Django 5.0.7 on 2024-11-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_contactmessage_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
    ]
