# Generated by Django 5.0.7 on 2024-11-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_delete_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="diet",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("keto", "Keto"),
                    ("paleo", "Paleo"),
                    ("gluten-free", "Gluten-Free"),
                    ("none", "No Restrictions"),
                ],
                default="none",
                help_text="Dietary preference for this recipe",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="spice_level",
            field=models.CharField(
                choices=[("mild", "Mild"), ("medium", "Medium"), ("hot", "Hot")],
                default="mild",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cuisine",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
