# Generated by Django 5.0.7 on 2024-11-14 10:53

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_diet_recipe_spice_level_alter_recipe_cuisine"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
